name: Check Makefile
on: push
jobs:
  install:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - if: ${{ matrix.os == "macos-latest" }}
        run: |
          brew install docker docker-machine
          brew install virtualbox --cask
          docker-machine create --driver virtualbox default
          eval $(docker-machine env default)
      - run: make install
